//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreOwnedVehicle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbldistrict
    {
        public tbldistrict()
        {
            this.tblcities = new HashSet<tblcity>();
            this.tblregs = new HashSet<tblreg>();
        }
    
        public int districtid { get; set; }
        public string districtname { get; set; }
    
        public virtual ICollection<tblcity> tblcities { get; set; }
        public virtual ICollection<tblreg> tblregs { get; set; }
    }
}
