//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreOwnedVehicle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfeedback
    {
        public int feedid { get; set; }
        public string feedback { get; set; }
        public string feedname { get; set; }
        public string subject { get; set; }
        public string email { get; set; }
        public Nullable<bool> isread { get; set; }
    }
}
