//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreOwnedVehicle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblinsurance
    {
        public int insuranceid { get; set; }
        public Nullable<int> loginid { get; set; }
        public Nullable<int> regid { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<System.DateTime> renewdate { get; set; }
    
        public virtual tbllogin tbllogin { get; set; }
        public virtual tblvehiclereg tblvehiclereg { get; set; }
    }
}
