//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreOwnedVehicle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbllogin
    {
        public tbllogin()
        {
            this.tblregs = new HashSet<tblreg>();
            this.tblvehicleregs = new HashSet<tblvehiclereg>();
            this.tblinsurances = new HashSet<tblinsurance>();
            this.tblpolicecomplaints = new HashSet<tblpolicecomplaint>();
            this.tblpollutions = new HashSet<tblpollution>();
            this.tblservices = new HashSet<tblservice>();
        }
    
        public int loginid { get; set; }
        public Nullable<int> roleid { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual ICollection<tblreg> tblregs { get; set; }
        public virtual ICollection<tblvehiclereg> tblvehicleregs { get; set; }
        public virtual ICollection<tblinsurance> tblinsurances { get; set; }
        public virtual ICollection<tblpolicecomplaint> tblpolicecomplaints { get; set; }
        public virtual ICollection<tblpollution> tblpollutions { get; set; }
        public virtual ICollection<tblservice> tblservices { get; set; }
    }
}
