//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreOwnedVehicle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblvehiclereg
    {
        public tblvehiclereg()
        {
            this.tblinsurances = new HashSet<tblinsurance>();
            this.tblpolicecomplaints = new HashSet<tblpolicecomplaint>();
            this.tblpollutions = new HashSet<tblpollution>();
            this.tblservices = new HashSet<tblservice>();
        }
    
        public int regid { get; set; }
        public Nullable<int> loginid { get; set; }
        public string vehicleid { get; set; }
        public Nullable<int> cityid { get; set; }
        public string briefdescription { get; set; }
        public string dealername { get; set; }
        public string address { get; set; }
        public string makername { get; set; }
        public string regownername { get; set; }
        public string permanentaddr { get; set; }
        public string classfvehicle { get; set; }
        public string typeofbody { get; set; }
        public string chassisno { get; set; }
        public string engineno { get; set; }
        public string fuel { get; set; }
        public string color { get; set; }
        public string yearofmanf { get; set; }
        public string seatcapacity { get; set; }
        public string tax { get; set; }
        public Nullable<System.DateTime> taxpaidon { get; set; }
        public string file1 { get; set; }
        public string mobile { get; set; }
    
        public virtual tblcity tblcity { get; set; }
        public virtual tbllogin tbllogin { get; set; }
        public virtual ICollection<tblinsurance> tblinsurances { get; set; }
        public virtual ICollection<tblpolicecomplaint> tblpolicecomplaints { get; set; }
        public virtual ICollection<tblpollution> tblpollutions { get; set; }
        public virtual ICollection<tblservice> tblservices { get; set; }
    }
}
